server:
  port: 10000
spring:
  application:
    name: job-eureka
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
