server:
  port: 9000 #服务端口
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/job?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: jwt-zuul #指定服务名
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
ribbon:
  ConnectTimeout: 600000 #请求处理的超时时间
  ReadTimeout: 600000 #请求连接的超时时间
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
zuul:
  sensitiveHeaders:
